Implemented authentication
Bit-Branch/Cinema pull request #1
Opened 2022-01-18 16:58 UTC by Bit-Branch

2022-01-19 13:16 UTC, bagatka requested changes

2022-01-19 13:16 UTC, bagatka commented on Server/Cinema/Cinema/Controllers/UsersController.cs
> +            return StatusCode(201, "You successfully registered, please log in with your credentials");
There is `BadRequest()` for 400, `Unauthorized()` for 401. What about 201?

2022-01-19 13:16 UTC, bagatka commented on Server/Cinema/Cinema/Program.cs
> +
```suggestion
```

2022-01-19 13:16 UTC, bagatka commented on Server/Cinema/Cinema/Properties/launchSettings.json
> +      "launchUrl": "weatherforecast",
Do you need it?

2022-01-19 13:16 UTC, bagatka commented on Server/Cinema/Cinema/Properties/launchSettings.json
> +    "anonymousAuthentication": true,
Why do you need it?

2022-01-19 13:16 UTC, bagatka commented on Server/Cinema/Cinema/Program.cs
> +    options.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
Is it possible to apply `using ...`?

2022-01-19 13:16 UTC, bagatka commented on Server/Cinema/Cinema/Program.cs
> +builder.Services.AddScoped<IUserService, UserService>();
Why `scoped`?

2022-01-19 13:16 UTC, bagatka commented on Server/Cinema/Cinema/Program.cs
> +    .AllowAnyMethod());
Let's discuss the following code style

```
app.UseCors(source =>
    {
        source
            .AllowAnyOrigin()
            .AllowAnyHeader()
            .AllowAnyMethod()
    }
);
```
```
app.UseCors(
    source =>
    {
        source
            .AllowAnyOrigin()
            .AllowAnyHeader()
            .AllowAnyMethod()
    }
);
```

```
app.UseCors(
    source =>
    {
        source.AllowAnyOrigin()
            .AllowAnyHeader()
            .AllowAnyMethod()
    }
);
```

2022-01-19 13:16 UTC, bagatka commented on Server/Cinema/Cinema/Program.cs
> +
I would suggest to remove it

2022-01-19 13:16 UTC, bagatka commented on Server/Cinema/Cinema/Program.cs
> +var builder = WebApplication.CreateBuilder(args);
Is there any other approach to configure and run WebApplication in ASP.NET Core?

2022-01-20 07:10 UTC, Bit-Branch commented on Client/cinema-app/package.json
> +    "@angular/animations": "~13.1.0",
I use this to stay within version 13.1.X and get new bug fixes, but don't want any potentially incompatible changes

2022-01-20 07:17 UTC, Bit-Branch commented on Client/cinema-app/src/app/shared/layout/login-dialog/login-pages.ts
> +type tPages = {
Like "type"
But yes, it's redundant here

2022-01-20 07:29 UTC, Bit-Branch commented on Client/cinema-app/src/app/shared/layout/login-dialog/login-pages.ts
> +type tPages = {
Both can be used to describe the structure of an object, but it's mainly purpose of the interfaces (provide the contract), while with types we give a new name to the type

1) with types we can create type aliases (f.e. unions)
2) with unions and intersections we can combine functionality ( but we can also use declaration merging in interfaces to achive this goal)
3) with types we can work with core ts types like string, number, etc.
4) type can be self-referencing
and syntax

But to describe my type in this case i want to switch to interface

2022-01-20 07:33 UTC, Bit-Branch commented on Client/cinema-app/src/app/shared/layout/login-dialog/login.component.css
> +::ng-deep .mat-form-field.mat-focused .mat-form-field-label {
This styles will apply to all elements with this classes in whole document
So we can get some style conflicts

2022-01-20 07:39 UTC, Bit-Branch commented on Client/cinema-app/src/app/shared/layout/login-dialog/login.component.html
> +<div [@vanish]="page">
This is the name of one of the animations defined in the login-animations.ts using angular animations
We bind it to a variable that will switch between the states

2022-01-20 07:40 UTC, Bit-Branch commented on Client/cinema-app/src/app/shared/layout/login-dialog/login.component.html
> +    <mat-form-field appearance="legacy" @inflate>
Animation with this name will play when element appears in DOM

2022-01-20 07:44 UTC, Bit-Branch commented on Client/cinema-app/src/app/shared/layout/login-dialog/login.component.ts
> +    switch(this.page = page) {
I create only one popup dialog for login and registration forms
So i use this method to change between forms and dynamically add/remove form controlls that needed (or not) in one of the forms

2022-01-20 07:49 UTC, Bit-Branch commented on Client/cinema-app/src/environments/environment.ts
> +  hostUrl: "https://localhost:7263"
To send requests to our server-side implementation (we need to know in which url server is hosted)

2022-01-20 08:01 UTC, Bit-Branch commented on Server/Cinema/Cinema.Service/JwtService.cs
> +                Expires = DateTime.Now.AddMinutes(_options.ExpiryInMinutes),
Seems like now we depending of server timezone
I think yes, i need to use UTC there

2022-01-20 08:03 UTC, Bit-Branch commented on Server/Cinema/Cinema.Service/UserService.cs
> +            string salt = BCrypt.Net.BCrypt.GenerateSalt();
Not with the BCrypt
It saves salt and hashed password in one 60 characters string divided by $

2022-01-20 08:08 UTC, Bit-Branch commented on Server/Cinema/Cinema/Controllers/UsersController.cs
> +    [ApiController]
We just return data from server to client, not rendering views 
But with Controller it also possible (to return data) but we need to add manually some code to convert data to JSON for example, while ApiController do it automatically
Also with this approach (just returning data, not render something) we are become independent of our client view implementation (client only should work with such data and able to have any view)

2022-01-20 08:27 UTC, Bit-Branch commented on Server/Cinema/Cinema/Controllers/UsersController.cs
> +                return BadRequest("User with this email is already exists");
With this message potential attacker(person or malware) will know about existence of user in our database
Users often use the same password in different resources
So if an attacker will get access to our existing user credentials in some other resource, it's really big chance that he can login with this credentials to our resource

2022-01-20 08:27 UTC, Bit-Branch commented on Server/Cinema/Cinema/Controllers/UsersController.cs
> +            return StatusCode(201, "You successfully registered, please log in with your credentials");
`Created()`

2022-01-20 10:08 UTC, Bit-Branch commented on Server/Cinema/Cinema/Program.cs
> +builder.Services.AddScoped<IUserService, UserService>();
I don't need to create a new instance of each service per every injection/request to service, because it can cause some overhead of time (we create (and release) a lot of different instances for many clients) 
So i choose `scoped` - we just create one service instance per each client scope

2022-01-20 10:09 UTC, Bit-Branch commented on Server/Cinema/Cinema/Program.cs
> +    options.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
Yes, fixed

2022-01-20 10:21 UTC, Bit-Branch commented on Server/Cinema/Cinema/Controllers/UsersController.cs
> +                return Unauthorized(new AuthResponseDto { ErrorMessage = "User name or password invalid" });
In this case we return 401 because we have problems with user credentials (wrong email or password) during authentication process (and this is not server-side fault)
We don't need to return 403 there, because we don't check for access of authenticated user to some resource - we check for existence of user with such credentials in our base

2022-01-20 10:32 UTC, Bit-Branch commented on Client/cinema-app/package.json
> +    "@angular/material": "^13.1.2",
Setted automatically with adding material dependency
We can update to newer versions of this dependency (13.X.X) and they potentially can provide some new functionality
Maybe in this case we can have some conflict between other dependencies that i use (or will use) because of newer version of this dependency
So i think i don't need `^` there

2022-01-20 10:50 UTC, Bit-Branch commented on Server/Cinema/Cinema/Program.cs
> +    .AllowAnyMethod());
First one looks good

2022-01-20 13:41 UTC, Bit-Branch commented on Client/cinema-app/src/app/shared/material.module.ts
> +export class MaterialModule { }
Maybe not
I put it in shared module and we can share it across all application
Although some modules don't need some of this material modules, but i import them all
So our application can grow in size 
I think i should divide this one across all modules

2022-01-25 16:01 UTC, bagatka requested changes

2022-01-26 15:45 UTC, andrei-kruhliakou-itechart commented on Server/Cinema/Cinema.Infrastructure/Services/UserService.cs
> +            var salt = BCrypt.Net.BCrypt.GenerateSalt();
Why BCrypt?

2022-01-26 15:45 UTC, andrei-kruhliakou-itechart commented on Server/Cinema/Cinema/appsettings.Development.json
> +    "ExpireIn": "00:30:00"
Why 30 minutes?

2022-01-26 15:45 UTC, andrei-kruhliakou-itechart commented on Server/Cinema/Cinema.Application/Interfaces/IJwtService.cs
> +    public interface IJwtService
Why do you need this interface?

Also why did you put it in Application assembly?

2022-01-31 11:16 UTC, Bit-Branch commented on Server/Cinema/Cinema/appsettings.Development.json
> +    "ExpireIn": "00:30:00"
When buying tickets, we actually buy the ticket itself on the site and then show it once at the checkout from this site (or email). Half an hour should be enough to purchase a ticket online. In addition, most people don't often buy tickets (some once a month, some less often), so another authentication after 30 minutes should not cause some inconvenience for users - they simply do not need to log into their account often when using such service (you need to lig in once to buy a ticket and once to show this purchase at the cinema box office, and then again for a long period of a month or more when going to the cinema is not planned).
But there is another problem - for now authentication is available using only an access token. If the potential attacker can obtain administrator token, then in 30 minutes (and even more if we set it for a longer period of time) he can do a lot of things.
Therefore, in order to not to give an attacker such possibility, as well as to remove an unconvenient moment with constant manual authentication for people who go to cinemas very othen (let's say, for example, twice a week), it's possible to add authentication via two tokens - access and refresh. Then it will be more difficult to potential attacker to obtain access to administrator account for a time sufficient to do something, and users, who go to the cinema several times a week will not have to constantly log into their personal account.

2022-01-31 11:27 UTC, Bit-Branch commented on Server/Cinema/Cinema.Infrastructure/Services/UserService.cs
> +            var salt = BCrypt.Net.BCrypt.GenerateSalt();
Initially, the choice was from three algorithms: pbkdf2, scrypt, bcrypt.
PBKDF2 is easily parallelized with GPUs.
BCrypt solves this problem and has been rliable for a long time.
SCrypt is considered more reliable than the previous two, but i did not find any more or less reliable packages with it's implementation.

On the other hand, PBKDF2 is officially supported by Microsoft, and using third-party packages (like BCrypt in this case) is already a security risk. So there was an alternative with PBKDF2 with a few thousand iterations, but i chose BCrypt.

2022-01-31 11:31 UTC, Bit-Branch commented on Server/Cinema/Cinema.Application/Interfaces/IJwtService.cs
> +    public interface IJwtService
At the application level we have contracts for business logic and it depends only on the domain level. For testing or a possible change of technologies, it will be enough for us to subsitute another implementation of the service, while the system will still work. 
Within my project, it's highly unlikely that i would have to substitute another implementation to create a token, so this abstraction seems redundant - our functionality for the token should not change.

2022-02-01 17:22 UTC, andrei-kruhliakou-itechart commented on Server/Cinema/Cinema.Application/Interfaces/IJwtService.cs
> +    public interface IJwtService
I would not say that this is the business logic of you application. Particular authentication token implementation looks more like infrastructure concern to me.

2022-02-02 09:03 UTC, bagatka approved these changes
Minor changes, that can be added in the next PR

2022-02-02 09:06 UTC, merged